server:
  port: 8089

spring:
  application:
    name: library-management
  datasource:
    url: jdbc:postgresql://localhost:15438/library-management
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET_KEY:RGVmaW5lWCZQYXRpa2FEZXYmVGFza01hbmFnZW1lbnQ=}
  expiration: ${JWT_EXPIRATION:3600000}
  issuer: library-management