services:
  task-management-postgres:
    container_name: library_postgres_container
    image: postgres:16.8-alpine
    environment:
      POSTGRES_DB: library-management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "15438:5432"
    volumes:
      - library-management-postgres-data:/var/lib/postgresql/data

volumes:
  library-management-postgres-data: